name: Build and Deploy Flutter Web

on:
  push:
    branches: [ master ]  # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configure o Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'  # substitua pela versão do seu projeto, se quiser

    - name: Pub get
      run: flutter pub get

    - name: Build web release
      run: flutter build web --release

    - name: Deploy build/web para o repositório netlify_portfolio_tech
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: luizzlcs/netlify_portfolio_tech
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./build/web
        publish_branch: master  # aqui você coloca a branch do seu repositório web
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
        # Se for um repositório separado, use:
        # external_repository: seu-usuario/seu-repo-web
        # personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
